version: '3'

services:
  test-web-server:
    image: nginx:latest
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${SITE_URL}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=leresolver"

networks:
  proxy:
    external: true
